### ISSUE TITLE
Capture Issues on Export

### ISSUE THREAD

**Issue by melMass** [sideeffects/HoudiniFBX#5]
Hi,

From the docs, it seems there is an issue with exporting skinning through FBX on mac? What is the issue exactly as any other DCCs handles it pretty well?

Here is my issue, I'm trying to export a rigged car but the `capture overrides` are not exporting right. The chain is capture > overrides > deform (no other nodes after as I know it messes up the exporter).

### Houdini Rig
![Houdini_RIG](https://user-images.githubusercontent.com/7041726/58747521-74a7d000-846c-11e9-9251-16193db95246.gif)

### Reimported FBX export
![Houdini_FBX](https://user-images.githubusercontent.com/7041726/58747529-a02aba80-846c-11e9-9b55-045b5037becc.gif)

I'm trying to build a pipeline using FBX to generate a bunch of car rigs & animations but I'm stuck with this issue. If someone has a clue I would be grateful.

**Comment by melMass** [comment]
### SOP Nodes
![image](https://user-images.githubusercontent.com/7041726/58747603-cb61d980-846d-11e9-8cc2-e612ae2216b4.png)

### Geo (subnet) Nodes
![image](https://user-images.githubusercontent.com/7041726/58747623-07953a00-846e-11e9-9f48-6c58598d87e8.png)

It might be important to note that the pivot nodes are set to `Keep position when parenting` and their initial position is calculated in another SOP network, they are not binded to the geometry in any way.

**Comment by e4lam** [comment]
You should try narrowing down the problem that you see after re-importing because it's really hard to tell from just pictures all alone. First check that the bones are animated correctly after re-importing by comparing with before the export. If that's correct, then confirm that the capture weights are different by looking at them in the geometry spreadsheet before and after export. Is there a pattern to what's wrong? Then try only using one override (the one where you need it for your animating door) and see if that works.

**Comment by melMass** [comment]
@e4lam Yes you are right. I'm going to narrow down the rig as you suggested before posting more infos

**Comment by melMass** [comment]
I actually got mislead by the warning in the docs. It was my mistake only.

From reading the source code I realised I had to add the root to the capture using a `capture region` inside the root null. It's now working as expected ;)

**Comment by e4lam** [comment]
That's not what I would expect to be the problem offhand. Which file and line number were you running into that required the capture region in the root? Can you describe the code path that was going wrong for you?
